# Generated by Django 5.1.2 on 2025-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='cpu',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='cpucooler',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='gpu',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='mobo',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='psu',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='ram',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='product_type',
            field=models.CharField(default='CPU', max_length=20),
        ),
    ]
