# Generated by Django 5.1.7 on 2025-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guidesimages_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidesimages',
            name='video_url',
        ),
        migrations.AddField(
            model_name='guides',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
