# Generated by Django 5.1.7 on 2025-05-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_remove_guidesimages_video_url_guides_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guide_images/'),
        ),
    ]
