# Generated by Django 5.1.7 on 2025-05-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_alter_guides_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guides',
            options={'verbose_name_plural': 'View Guides'},
        ),
    ]
