# Generated by Django 5.1.2 on 2025-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_case_product_type_cpu_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='product_type',
            field=models.CharField(default='CASE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='product_type',
            field=models.CharField(default='CPUCooler', max_length=20),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='product_type',
            field=models.CharField(default='GPU', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobo',
            name='product_type',
            field=models.CharField(default='MOBO', max_length=20),
        ),
        migrations.AlterField(
            model_name='psu',
            name='product_type',
            field=models.CharField(default='PSU', max_length=20),
        ),
        migrations.AlterField(
            model_name='ram',
            name='product_type',
            field=models.CharField(default='RAM', max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product_type',
            field=models.CharField(default='Storage', max_length=20),
        ),
    ]
